fix

diff --git a/.github/workflows/general.yml b/.github/workflows/general.yml
--- a/.github/workflows/general.yml
+++ b/.github/workflows/general.yml
@@ -35,6 +35,40 @@ jobs:
         echo "Updated $FILE_PATH:"
         cat $FILE_PATH
 
+    - name: ✏️ Update jsconfig.json Base URL
+      run: |
+          # Define the jsconfig.json file path
+          JSCONFIG_PATH="jsconfig.json"
+
+          # Ensure the jsconfig.json file exists
+          if [ ! -f "$JSCONFIG_PATH" ]; then
+            echo "Error: $JSCONFIG_PATH not found!" && exit 1
+          fi
+
+          # Update baseURL in jsconfig.json
+          sed -i "s|baseURL: '""'|baseURL: './dashboard-v3/'|" $FILE_PATH
+
+          # Confirm the update
+          echo "Updated $JSCONFIG_PATH:"
+          cat $JSCONFIG_PATH
+
+    - name: ✏️ Update vite.config.js Base URL
+      run: |
+              # Define the vite.config.js file path
+              VITECONFIG_PATH="vite.config.js"
+
+              # Ensure the vite.config.js file exists
+              if [ ! -f "$VITECONFIG_PATH" ]; then
+                echo "Error: $VITECONFIG_PATH not found!" && exit 1
+              fi
+
+              # Update base in vite.config.js
+              sed -i "s|base: '""'|base: '/dashboard-v3/'|" $FILE_PATH
+
+              # Confirm the update
+              echo "Updated $VITECONFIG_PATH:"
+              cat $VITECONFIG_PATH
+
     - name: 🔨 Build Project
       run: |
         npm install
